name: Go
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

      - name: Set up Go 1.13
        uses: actions/setup-go@v1
        with:
          go-version: 1.13
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v1

      - name: Get dependencies
        run: |
          go get -v -t -d ./...
          if [ -f Gopkg.toml ]; then
              curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
              dep ensure
          fi

      - name: Build Exchange Rate
        run:  cd forex && go build -v .
      - name: Test Exchange Rate
        run:  cd forex && go test -run ''


      - name: Build Technical Indicator
        run:  cd technical_indicator && go build -v .
      - name: Test Technical Indicator
        run:  cd technical_indicator && go test -run ''

      - name: Build crypto
        run:  cd crypto && go build -v .

      - name: Test crypto
        run:  cd crypto && go test -run ''

      - name: Build Time Series
        run:  cd time_series && go build -v .
      - name: Test Time Series
        run:  cd time_series && go test -run ''
